# Generated by Django 6.0.1 on 2026-02-01 11:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_models', '0001_initial'),
        ('order_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='customer_models.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Списание'), ('CREDIT', 'Начисление')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet_models.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pay_type', models.CharField(choices=[('CAPTURE_ORDER', 'Оплата заказа'), ('REFUND_ORDER', 'Возврат оплаты')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order_models.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='wallet_mode_order_i_fa8f9b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['customer'], name='wallet_mode_custome_3c4c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet'], name='wallet_mode_wallet__54a9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_mode_wallet__fb50c1_idx'),
        ),
    ]
