# Generated by Django 6.0 on 2025-12-06 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerORM',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(unique=True)),
                ('operation', models.CharField(choices=[('CAPTURE_ORDER', 'Оплата заказа'), ('REFUND_ORDER', 'Возврат оплаты')])),
                ('request_hash', models.CharField()),
                ('response_payload', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['request_hash'], name='main_idempo_request_95b887_idx'), models.Index(fields=['key'], name='main_idempo_key_91bbd2_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderORM',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING', 'В обработке'), ('PAID', 'Оплачен'), ('REFUNDED', 'Возврат'), ('CANCELLED', 'Отменён')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='main.customerorm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentORM',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pay_type', models.CharField(choices=[('CAPTURE_ORDER', 'Оплата заказа'), ('REFUND_ORDER', 'Возврат оплаты')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='main.orderorm')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='main_paymen_order_i_9e2a58_idx')],
            },
        ),
    ]
