# Generated by Django 5.2.5 on 2026-01-11 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_id', models.UUIDField()),
                ('aggregate_type', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('event_version', models.CharField(default='1.0', max_length=10)),
                ('event_data', models.JSONField()),
                ('sequence_number', models.BigIntegerField()),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemORM',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField()),
                ('customer_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('items_count', models.IntegerField(default=0)),
                ('created_at_read', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_id', models.UUIDField()),
                ('aggregate_type', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('event_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WalletORM',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransactionORM',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Списание'), ('CREDIT', 'Начисление')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='WalletView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transactions_count', models.IntegerField(default=0)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='idempotencykey',
            name='main_idempo_key_91bbd2_idx',
        ),
        migrations.RemoveField(
            model_name='customerorm',
            name='balance',
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerorm',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='operation',
            field=models.CharField(choices=[('CREATE_ORDER', 'Создание заказа'), ('CAPTURE_PAYMENT', 'Подтверждение оплаты'), ('REFUND_ORDER', 'Возврат заказа')]),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='request_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='idempotencykey',
            unique_together={('key', 'user_id', 'operation')},
        ),
        migrations.AddIndex(
            model_name='customerorm',
            index=models.Index(fields=['id'], name='main_custom_id_cde36c_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['key', 'user_id', 'operation'], name='main_idempo_key_a78fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderorm',
            index=models.Index(fields=['customer', 'status'], name='main_ordero_custome_496028_idx'),
        ),
        migrations.AddIndex(
            model_name='orderorm',
            index=models.Index(fields=['customer'], name='main_ordero_custome_98f840_idx'),
        ),
        migrations.AddIndex(
            model_name='eventstore',
            index=models.Index(fields=['aggregate_id', 'aggregate_type'], name='main_events_aggrega_30a67d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventstore',
            index=models.Index(fields=['aggregate_id', 'aggregate_type', 'sequence_number'], name='main_events_aggrega_1290d5_idx'),
        ),
        migrations.AddField(
            model_name='orderitemorm',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.orderorm'),
        ),
        migrations.AddIndex(
            model_name='ordersummary',
            index=models.Index(fields=['customer_id', 'status'], name='main_orders_custome_562383_idx'),
        ),
        migrations.AddIndex(
            model_name='ordersummary',
            index=models.Index(fields=['customer_id', '-created_at_read'], name='main_orders_custome_a2cc58_idx'),
        ),
        migrations.AddIndex(
            model_name='ordersummary',
            index=models.Index(fields=['status'], name='main_orders_status_55fb84_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['processed', 'created_at'], name='main_outbox_process_af7606_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['aggregate_id', 'aggregate_type'], name='main_outbox_aggrega_9e0efb_idx'),
        ),
        migrations.AddField(
            model_name='walletorm',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='main.customerorm'),
        ),
        migrations.AddField(
            model_name='wallettransactionorm',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='main.walletorm'),
        ),
        migrations.AddIndex(
            model_name='walletview',
            index=models.Index(fields=['customer_id'], name='main_wallet_custome_e83cae_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemorm',
            index=models.Index(fields=['order'], name='main_orderi_order_i_639122_idx'),
        ),
        migrations.AddIndex(
            model_name='walletorm',
            index=models.Index(fields=['customer'], name='main_wallet_custome_cfa197_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransactionorm',
            index=models.Index(fields=['wallet'], name='main_wallet_wallet__b3bd5e_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransactionorm',
            index=models.Index(fields=['wallet', 'created_at'], name='main_wallet_wallet__6250b4_idx'),
        ),
    ]
