# Generated by Django 6.0.1 on 2026-02-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('CREATE_ORDER', 'Создание заказа'), ('CAPTURE_PAYMENT', 'Подтверждение оплаты'), ('REFUND_ORDER', 'Возврат заказа')])),
                ('request_hash', models.CharField(max_length=255)),
                ('response_payload', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['request_hash'], name='service_mod_request_b9fbe5_idx'), models.Index(fields=['key', 'user_id', 'operation'], name='service_mod_key_a14b73_idx')],
                'unique_together': {('key', 'user_id', 'operation')},
            },
        ),
    ]
